apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-sample-service-image
spec:
  params:
    - name: snapshotPath
    - name: dataPath
  steps:
    - name: push-image
      image: quay.io/redhat-appstudio/release-service-utils
      script: |
        set -eux

        echo "simulate pushing image!!!"
      workingDir: $(workspaces.data.path)
  workspaces:
    - name: data