apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: cc-sample-service-policy
  namespace: chcao-tenant
spec:
  configuration:
    include:
      - '@builtin'
  description: Includes rules for shipping sample-service
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Default
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:latest
