apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
 labels:
   release.appstudio.openshift.io/auto-release: 'true'
 name: cc-sample-service
 namespace: chcao-tenant
spec:
 application: sample-service
 target: chcao-tenant
 