kind: Deployment
apiVersion: apps/v1
metadata:
  name: errata-devel
  labels:
    app: errata-rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: errata-rails
  template:
    metadata:
      labels:
        app: errata-rails
    spec:
      containers:
        - image: images.paas.redhat.com/exd-sp-guild-errata/erratatool:latest
          name: errata-tool
