apiVersion: v1
kind: Service
metadata:
  name: errata-tool-service
  namespace: default
  labels:
    app: errata-tool
spec:
  selector:
    app: errata-tool
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: NodePort
